### ISSUE TITLE
Image fails to start on linux/arm/v7

### ISSUE THREAD

**Issue by awbn** [sdwilsh/brultech-serial2mqtt#107]
The image fails to run with `exec /bin/sh: exec format error` on a Raspberry Pi 2 (i.e., `linux/arm/v7` architecture). This usually indicates an incompatible architecture. Similarly, if I try to build the image on the RPi 2 (not recommended, it takes forever) it tries to pull the arm64 base image and fails. 

The `ghcr.io/linuxserver/baseimage-ubuntu:focal` image/tag itself is multi-platform; is there a reason to use distinct tags for arm/v7 and arm64 in the Dockerfile's `FROM` statement? If I simplify and generalize it to `FROM ghcr.io/linuxserver/baseimage-ubuntu:focal` it builds and runs correctly on all three architectures (verified on an RPi 2, RPi 4b, and an amd64 host). `docker buildx` with multiple platforms will also pull the the right image at the right time.

Other than the issue with pulling/building, the project works well on an old RPi 2!

**Comment by sdwilsh** [comment]
Just a heads up; at least for now I need to drop support for the Pi 2 because the upstream image I'm using no longer supports arm v7.

If you still need it, we can try to work on top of a new image, but I'd prefer if we didn't have to support it :)
