### ISSUE TITLE
Lack of clarity in compose example?

### ISSUE THREAD

**Issue by scyto** [sdwilsh/brultech-serial2mqtt#118]
I am getting this ERROR:
```
Attaching to brultech-serial2mqtt
Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/pi/brultech-serial2mqtt/config" to rootfs at "/config" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
Can you confirm that the image expects a host file called `<somepath>/config` to be mapped to a file in the root of the container called `/config` ?  

Or is your /conf actually supposed to be a volume?  if it is could you confirm what the configuration file is called, it isn't documented as far as i can see.... :-)

**Comment by scyto** [comment]
ah, looking at the project code i see you are actually looking for config/config.yml - you might want to update the compose example / be more detailed (i can probably help out with a docs pull request)

**Comment by sdwilsh** [comment]
I'd happily take a PR!  If not I can add a comment and make it more clear that it's looking for that specific file name in the configuration docs.
